server:
  port: 9000


management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,info
        base-path: /

spring:
  datasource:
    url: jdbc:h2:mem:empdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2 :
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
